### ISSUE TITLE
Using Macs since 1984 but new to GitHub

### ISSUE THREAD

**Issue by Mudflapper** [stefanzweifel/feedback#2]
Hi stefanzweifel. 

I thought I was pretty good with Macs and considered myself an advanced user until I joined GitHub and tried to figure out how to install these files! I wish it was as easy as double-clicking a PKG installer. 

The way i understood it, I used the default location when adding the IFTTT recipe and I created a folder named "up-export" inside the Apps folder in my Dropbox folder on my machine. Then I cloned the GitHub up-to-dayone folder inside that up-export folder.

But now I opened toDayOne.sh with Text Wrangler and it shows:

Modify the following variable to your needs. The folder should only contain log-files
LOGDIR='up-logs/'

But I'm not sure where that should be? Am I close?

So sorry to bug you but I'm dealing with some health issues and your script would really help me monitor my health more accurately so I can present info to my doctor. Think you could give me a hand? 

And I'm new to this so forgive me if this was the wrong place to request remedial help.

Thanks for creating this script!

**Comment by stefanzweifel** [comment]
Hi Mudflapper

Sorry to hear, that you had problems get the script running. But I would really like to help you. (And welcome to Github!).

You were really close with setting up your folders, but I think a Screenshot says a bit more. Here you see my structure:

![up-to-dayone](https://cloud.githubusercontent.com/assets/1080923/5871286/46f24914-a2db-11e4-8fff-7404cfafb419.png)

As I understand your post. You have nearly the same structure. Am I right? 

So when you cloned the script into your `up-export` folder you don't have to change the LOGDIR variable. Then after you cloned the script, there is already a folder `up-logs` in your `up-export` directory.

Know you only have to open your terminal and `cd` into your `up-export` folder. (Best thing is to type `cd ` into your terminal and than drag and drop the `up-export` folder into your terminal)

Then you have to call the script like so:
```
sh toDayOne.sh
```

I hope this helps you with your problem. If not, just add a comment to this post, together we can fix that :)

I will also add some more documentation to my article ([Github Issue](https://github.com/stefanzweifel/up-to-dayone/issues/2)), so it will be clearer for others to setup the script. I personally use a simple [Alfred Workflow](http://www.alfredapp.com/) to call the script. I will add this to the docs to.

:v:

**Comment by stefanzweifel** [comment]
It's me again.
I updated my post about setting up the script (stefanzweifel/stefanzweifel.io@061438df39ec1fff52a2f59f569641d8343d7f07).

Post: https://stefanzweifel.io/posts/jawbone-up-to-dayone/

I hope this will help you getting everything setup correctly.
I will close this issue know. If you have further problems, reopen it.

**Comment by Mudflapper** [comment]
Hi again, sorry I haven't responded sooner. Thanks again for your help and patience with my newfound ineptitude ;) 

The text files are appearing the the up-logs directory. I used terminal to CD into the up-export directory and launch the script, but I get an error in line 27 (day one: command not found) then it deletes all the log files. I had 4 files in there. I used Time Machine to recover them and put them in a folder named "up-logs backup safety" for safekeeping so I can troubleshoot.

I've installed the DayOne CLI package. Do I need to tell it where the dayone cli app is?

![screen shot 2015-01-26 at 4 06 01 pm](https://cloud.githubusercontent.com/assets/10179758/5909333/40364dea-a575-11e4-8287-2c5b1c0f40ec.png)
![screen shot 2015-01-26 at 3 37 36 pm](https://cloud.githubusercontent.com/assets/10179758/5909334/403f2b54-a575-11e4-8488-9f61e4e76623.png)
![screen shot 2015-01-26 at 3 36 58 pm](https://cloud.githubusercontent.com/assets/10179758/5909335/404348ec-a575-11e4-801f-44a9ff1c61ba.png)

**Comment by stefanzweifel** [comment]
Hm, this is odd.
I installed my "dayone CLI" into the default directory and it worked right out of the box.

Could you post here, what you get when you type `which dayone` in your terminal? This should display the absolute path to the CLI.

Then you could modify [this line here](https://github.com/stefanzweifel/up-to-dayone/blob/master/toDayOne.sh#L27). Instead of just `dayone` you would reference the full path to the binary. Like so: `/usr/local/bin/dayone`.

And sorry that my script deleted the files. I try to implement a security net, so files shouldn't be deleted, if it can't be imported to Dayone.

**Comment by stefanzweifel** [comment]
I updated the script to automatically get the correct path of the `dayone`-binary.

Just download the latest version (not the release 1.0.0) or execute `git pull` in your `up-export` directory.

**Comment by Mudflapper** [comment]
Thanks Stefan.

Sorry it takes me a while to respond. I’m taking care of a sick mom.

I’ll download the new version asap. Later today, for sure.

I think I may have discovered the cause: I got a free copy of DayOne a few years as some sort of promotion—I can’t remember exactly but it was very new. It updates through the app, not the App Store. So I’m wondering if the CLI portion isn’t executable because of that? When you install the CLI package, it says that the CLI won’t work unless DayOne.app is purchased. So perhaps it thinks my copy isn’t legit. 

If that’s the case then I’ll just purchase a new copy. It’s worth every penny.

Thank,

Steve

**Comment by Mudflapper** [comment]
Ok, I (re)purchased DayOne just to be sure. I installed your latest version. Double checked my directories. Still not working. "which dayone" returns nothing.

I did find a hint here at this link: https://dayone.zendesk.com/hc/en-us/articles/200397200-Command-Line-CLI-Troubleshooting-Tips

I could not access my bin folder so I ran "sudo chmod +rx /usr/local/bin" so now "which dayone" returns the correct location: /usr/local/bin/dayone.

Still, I cd "/Volumes/Internal/Dropbox/apps/up-export" then enter "sh toDayOne.sh" and I get:

Read file: *
toDayOne.sh: line 30: *: No such file or directory
rm: *: No such file or directory
Done!

It feels like I'm getting closer?

Again, apologies for my relative newbness when it comes to github. I was initially confused because when I git clone the resulting directory is "up-to-dayone" when the actual folder name should be "up-export" so it works with the default logdir.

**Comment by stefanzweifel** [comment]
Hi Steve

Sounds like we're on the right track know. I've made some updates to the script ([Check if export worked](https://github.com/stefanzweifel/up-to-dayone/commit/8da0e4152da3fb912492ee29ee7e86a3fb3733be), [Files available](https://github.com/stefanzweifel/up-to-dayone/commit/349b02d641a66115011c2efe0c4d34bc594b2e7a)).

Now the script should give you better error messages, why something doesn't work. From what you have posted in your last comment, it looks like you don't have any logs in your `up-logs`-Folder. If you update the script and execute it again, you should know see an error message. The script also displays the full path where it looks for those Text-Files.

In addition, the script doesn't delete log files, if something went wrong while importing them into DayOne.app.

And I also recorded a short screencast / video (without any comments), where you see how my current setup looks like. [Link to Video](http://f.wnx.ch/v2Loih2oIXUP/Screen-Recording-2015-01-30-20-05-29.mp4).

Also a short description, how the script works:

> The script simply `cd`s into a given directory (for example `up-logs`). Then it gets the filenames of all files in the given directory. Then it loops through those filenames and extracts year, month and day from the filename. With those information the `dayone` command is called and the content of the file is pushed into Dayone.app. If everything worked correctly, the used file is removed from the disk.

**Comment by Mudflapper** [comment]
Stefan!

I didn’t update to your latest version yet. But I restarted today and ran the previous version of the script again (before I saw your response) and it worked!

Thanks for all your help. 

I see you use Alfred to run the script. I’ve used Butler for ages and was suspicious when a similar utility called Alfred was released, so I just stuck with Butler.

I think I’ll use Apple’s Automator to set up a folder action to watch the up-logs folder and automatically run the script whenever a new log file is generated.

Have you thought about creating an installer that would do all of this automatically? The installer could download and run the dayone cli installer, then simply ask the user for their Dropbox folder location (drag and drop, perhap?) then install the up-export directory and files in the proper location, as well as install an Automator executable that watches the up-log folder for newly-generated log files and runs the script automatically. 

Just a thought.

I’ll install the new script first chance I get later today.

Thanks again sir.

Steve

**Comment by stefanzweifel** [comment]
Hey Steve.

Great. I'm glad we got the script working.

Thanks for your idea for an installer. Sadly, I don't have any idea on how to create such an installer... but I will note the idea and eventually add such an installer in the future.

I really like the idea of an Automator script. Sadly, I don't have an idea of Automator either. Maybe you could share your Automator script and I would add it to the documentation and project?
